@host = http://localhost:8003
@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc0OTcwNDQ1LCJpYXQiOjE3NzQ5NjY4NDUsImp0aSI6ImUzMTk5ZDcyMDNjNTQ1N2JhMjQwMGNiNzIwMjM4MDgyIiwidXNlcl9pZCI6Niwicm9sZXMiOlsiYWRtaW4iXX0.YdWqLjwpUO8g3frXtO9RZWIzpOxQQ1n91B6WuTM1Sy8
@refresh_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3NTU3MTY0NSwiaWF0IjoxNzc0OTY2ODQ1LCJqdGkiOiJmZjQwM2FjZmEzYmU0OTM3OGE5ZjA5MzQ1YzM3MzNlZiIsInVzZXJfaWQiOjYsInJvbGVzIjpbImFkbWluIl19.7HTSupR3LvrbRK1-MC9d6kb23U1TIxWvjpvvBXQNfxc
# 1) Register user (public)
### User registration
POST {{host}}/api/users/register/
Content-Type: application/json

{
  "email": "testuser@example.com",
  "password": "StrongPass123",
  "password_confirm": "StrongPass123",
  "first_name": "Test",
  "last_name": "User"
}

# 2) Login user (public)
### User login
POST {{host}}/api/users/login/
Content-Type: application/json

# {
#   "email": "testuser@example.com",
#   "password": "StrongPass123"
# }

{
  "email": "lovedaniel@example.net",
  "password": "TestPass1234"
}


# 3) Refresh token via custom endpoint (requires access token)
### Custom refresh_token
POST {{host}}/api/users/refresh_token/
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "refresh": "{{refresh_token}}"
}

# 6) Get current user info (requires access token)
### Current user (me)
GET {{host}}/api/users/me/
Authorization: Bearer {{access_token}}


# 4) List users (requires access token)
### List users
GET {{host}}/api/users/
Authorization: Bearer {{access_token}}


# 5) Get user by id (requires access token)
### Get user detail
GET {{host}}/api/users/1/
Authorization: Bearer {{access_token}}


# 6) Update user (requires access token)
### Partial update user
PATCH {{host}}/api/users/1/
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "first_name": "Test2"
}

# 7) Assign role (admin only)
### Assign user role
POST {{host}}/api/users/1/assign_role/
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "role": "agent"
}

# 8) Logout (requires access token)
### Logout
POST {{host}}/api/users/logout/
Authorization: Bearer {{access_token}}


# 9) OpenAPI docs
### Swagger JSON
GET {{host}}/swagger.json

### Swagger UI
GET {{host}}/swagger/

### ReDoc
GET {{host}}/redoc/
